Fix: Styles update event not being emitted
vtex-apps/render-runtime pull request #572
Opened 2020-10-14 20:00 UTC by juliomoreira

#### What does this PR do?

Fixes a bug where updating styles would no emit events thus not hot-reloading styles.

[Issue on Store Discussion](https://github.com/vtex-apps/store-discussion/issues/435).

#### How to test it? \*

- Go to [Workspace](https://styles--beightoneagency.myvtex.com/pao?_q=pao&map=ft)
- Link an app or theme that has styles.json or css overrides.
- Make changes on any styles files.
- Observe that hot-reloading now works.

#### Describe alternatives you've considered, if any. \*

N/A

#### Related to / Depends on \*

N/A

2020-10-14 21:34 UTC, klzns requested changes
Thanks for this PR! ❤️

2020-10-14 21:34 UTC, klzns commented on CHANGELOG.md
> +### Fix
```suggestion
### Fixed
```

2020-10-14 21:43 UTC, juliomoreira commented on CHANGELOG.md
> +### Fix
Done!

2020-10-23 17:14 UTC, tlgimenes approved these changes

2020-10-23 18:12 UTC, klzns approved these changes

2020-10-23 18:47 UTC, merged