Make render8 pages work for stores running on portal
vtex-apps/render-runtime pull request #580
Opened 2020-10-29 22:24 UTC by salesfelipe

#### What does this PR do? \*

- ditto.

#### How to test it? \*

- https://feirissima.vtexcommercestable.com.br/_secure/account?workspace=felipe
- visit the Subscriptions on my-account page

#### Describe alternatives you've considered, if any. \*

#### Related to / Depends on \*

2020-10-30 13:15 UTC, Klynger requested changes

2020-10-30 13:15 UTC, Klynger commented on react/utils/host.ts
> +  return isServerdThroughJanus ? false : !!isRender8
Typo
```suggestion
  return isServedThroughJanus ? false : Boolean(isRender8)
```

2020-10-30 13:15 UTC, Klynger commented on react/utils/host.ts
> +  const isRender8 = generator && generator.startsWith('vtex.render-server')
```suggestion
  const isRender8 = generator?.startsWith('vtex.render-server')
```

2020-10-30 13:15 UTC, Klynger commented on react/utils/host.ts
> +  const isServerdThroughJanus = window.location.pathname.startsWith('/api/io')
Typo
```suggestion
  const isServedThroughJanus = window.location.pathname.startsWith('/api/io')
```

2020-10-30 13:15 UTC, Klynger commented on react/utils/host.ts
> +  return isServerdThroughJanus ? false : !!isRender8
```suggestion
  return !isServedThroughJanus && Boolean(isRender8)
```

2020-10-30 13:17 UTC, Klynger commented
I didn't understand how to test it and when I open the URL I just see this:

![image](https://user-images.githubusercontent.com/8517023/97709414-0f10a680-1a99-11eb-8e9e-c18578b0a130.png)

2020-10-30 13:19 UTC, salesfelipe commented
> I didn't understand how to test it and when I open the URL I just see this:
> 
> ![image](https://user-images.githubusercontent.com/8517023/97709414-0f10a680-1a99-11eb-8e9e-c18578b0a130.png)

You have to login to access the my-account then go to the subscriptions section.

2020-10-30 13:39 UTC, Klynger approved these changes

2020-11-16 21:01 UTC, kevinch approved these changes
Looks good but i'm not the best expert for the render-runtime.

2020-11-17 17:31 UTC, brunoabreu approved these changes

2020-11-17 20:28 UTC, lbebber commented
![Screen Shot 2020-11-17 at 17 27 39](https://user-images.githubusercontent.com/5691711/99443908-3a4d1f80-28fa-11eb-9934-f25b113a450b.png)
to be sure, is this expected? (i.e. the lack of proper messages)

2020-11-17 20:29 UTC, salesfelipe commented
> ![Screen Shot 2020-11-17 at 17 27 39](https://user-images.githubusercontent.com/5691711/99443908-3a4d1f80-28fa-11eb-9934-f25b113a450b.png)
> to be sure, is this expected? (i.e. the lack of proper messages)

Yes, I had to fix this on the my-subscriptions app, the problem is the `store/` prefix...

2020-11-17 20:31 UTC, lbebber approved these changes
LGTM just be extra careful with the release 🙏

2020-11-17 20:32 UTC, salesfelipe commented
> LGTM just be extra careful with the release 🙏

:harold-pain:

2020-12-02 16:49 UTC, merged