Add full documentation
vtex-apps/render-runtime pull request #582
Opened 2020-11-12 18:31 UTC by klzns

#### What does this PR do? \*

Add docs to render-runtime! 

#### How to test it? \*

Reading it.

#### Describe alternatives you've considered, if any. \*

We should add some JSDoc too, but we can do that later.

#### Related to / Depends on \*

2020-11-12 18:49 UTC, kaisermann requested changes

2020-11-12 18:49 UTC, kaisermann commented on docs/README.md
> +A React hook that provides some functions and variables that are useful when creating components.
```suggestion
A React hook that provides runtime contextual variables and methods to help creating components.
```

2020-11-12 18:49 UTC, kaisermann commented on docs/README.md
> +A `history` object reexported from history package.
```suggestion
A `history` object reexported from the `history` package. 
```

2020-11-12 18:49 UTC, kaisermann commented on docs/README.md
> +A _function_ that should be use to make a client-side navigation.
```suggestion
A _function_ that must be used to make a client-side navigation.
```

2020-11-12 18:49 UTC, kaisermann commented on docs/README.md
> +A _string_ value of the current page.
Representing what? The URL?

2020-11-12 18:49 UTC, kaisermann commented on docs/README.md
> +A _boolean_ value whether is in a production workspace or not.
```suggestion
A _boolean_ value representing whether the app is in a production workspace or not.
```

2020-11-12 18:49 UTC, kaisermann commented on docs/README.md
> +A React component that renders an `a` HTML element that, when clicked, navigates the user to the provided route. It has a similar API with the `navigate` method.
```suggestion
A React component that renders an `a` HTML element that, when clicked, navigates the user to the provided route. It has a similar API to the `navigate` method.
```

2020-11-12 19:02 UTC, klzns commented on docs/README.md
> +A _string_ value of the current page.
Good point!

2020-11-12 19:06 UTC, kaisermann approved these changes

2020-11-12 19:06 UTC, kaisermann commented on docs/README.md
> +This app handles runtime execution of React apps in the VTEX IO Platform and exports some helpful React components, React hooks and variable.
```suggestion
This app handles runtime execution of React apps in the VTEX IO Platform and exports some helpful React components hooks and variables.
```

2020-11-12 19:06 UTC, kaisermann commented on docs/README.md
> +> **Tip:** run `vtex setup --typings` to add vtex.render-runtime types in your app. This will provide autocomplete features in VSCode.
```suggestion
> **Tip:** run `vtex setup --typings` to add `vtex.render-runtime` types in your app. IDEs can use them to provide autocomplete for variables and methods.
```

2020-11-16 17:17 UTC, victorhmp requested changes

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +  return <div>Hello</div>
```suggestion
  return <div>This {hints.desktop ? 'is' : 'is not'} a desktop</div>
```

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +  return <div>Hello</div>
```suggestion
  return <div>This is the current page id: {page}</div>
```

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +  return <div>Hello</div>
```suggestion
  return <div>This {production ? 'is' : 'is not'} a production workspace</div>
```

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +  return <div>Hello</div>
```suggestion
  return <div>This page is rendered using vtex.render-runtime@{renderMajor}.x</div>
```

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +}
Could not think of a good example here, but we should also use the `rootPath` variable in some way here.

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +  return <div>Hello</div>
```suggestion
  return <div>This is the {workspace} workspace</div>
```

2020-11-16 17:17 UTC, victorhmp commented on docs/README.md
> +A React component that is used to create Store Framework blocks that expects a specific block id.
We could add a disclaimer here, telling people that they should use `Block` or `ExtensionPoint` if they expect to receive blocks via the `blocks` array.

2020-11-16 19:03 UTC, victorhmp approved these changes

2020-11-19 18:52 UTC, carolinamenezes commented
@klzns @victorhmp atualizei o readme. se vocês não tiverem gostado dessa estrutura que coloquei, é só me falar que a gente volta hehe

2020-11-24 13:11 UTC, merged