added tachyons class
vtex-apps/render-runtime pull request #640
Opened 2022-10-10 14:02 UTC by Ienzi

#### What does this PR do? \* This PR provides a tachyons class in order to modify its CSS directly from the theme. The problem was related to this component: https://github.com/vtex-apps/render-runtime/blob/1aa78341198fed752c4785aadce04e38d7ccdae5/react/components/ExtensionPoint/index.tsx#L164 that inherits the bg color from the body. Adding this class the developer is able to customize such block, If he wants a different background, simply add it inside the **style.json** file, section _background_.

#### How to test it? \* This is the workspace: https://checkoutiopr--ukccwhirlpool.myvtex.com/cart#/ . To replicate: add a product and go to the cart. this is without the className: 
![image](https://user-images.githubusercontent.com/115475534/194883564-d9c940ad-4502-4d0f-babd-6ed260a47e0e.png)
 and this with the class added: 
![image](https://user-images.githubusercontent.com/115475534/194883471-ab752bb3-d4ab-41b6-abfe-58442c018257.png)

#### Describe alternatives you've considered, if any. \* 
- Considered other names for such class;
- Tried with cssHandles but failed because of a dependency cycle detected: 
![image](https://user-images.githubusercontent.com/115475534/194883988-61d018af-f0b2-4840-a111-a9cc7d163c42.png)

#### Related to / Depends on \*

2022-12-12 19:40 UTC, danzanzini commented
Hello @Ienzi, can you clarify what color this new class is changing? I couldn't see by the images you sent

2022-12-14 14:00 UTC, danzanzini requested changes
Hey @Ienzi, thanks for the contribution.

Left one suggestion for the name of the class.

2022-12-14 14:00 UTC, danzanzini commented on react/components/ExtensionPoint/index.tsx
> +      {isRootTreePath && <div className="flex flex-grow-1 bg-checkout-color" />}
An ExtensionPoint is used in many situations, so the name should be more generic than this.

```suggestion
      {isRootTreePath && <div className="flex flex-grow-1 below-element" />}
```

2022-12-16 08:45 UTC, Ienzi commented
Hello @danzanzini, I've confirmed your changes, please keep me posted!

2022-12-20 18:55 UTC, danzanzini approved these changes

2022-12-22 13:33 UTC, merged

2022-12-22 13:43 UTC, danzanzini commented
Hello @Ienzi. Just did the merge. Can you install it on your store and check if everything is ok?

2022-12-27 14:50 UTC, Ienzi commented
Hi @danzanzini in order to work it should be "bg-below-element" not just "below-element"